---
# tasks file for remove_old_packeges_on_debian

- name: Delete old packeges
  ansible.builtin.apt:
    name: "{{ item }}"
    state: absent
  loop: "{{ old_packeges }}"
  when: old_packeges is defined and old_packeges | length > 0 and ansible_distribution == 'Debian' and ansible_distribution_version | int >= 11
  notify:
    - Cleanup complete
