---
# tasks file for remove_old_packeges_on_debian

- name: Delete old packeges
  ansible.builtin.apt:
    name: libdns-export1104
    state: absent
  when: ansible_distribution == 'Debian' and ansible_distribution_version | int >= 11
