---
# tasks file for auditd_install

- name: Install auditd
  ansible.builtin.apt:
    name: auditd
    state: present
    update_cache: yes
  when: ansible_distribution == 'Debian'

- name: Auditd cofiguration
  ansible.builtin.copy:
    src: audit.rules
    dest: "/etc/audit/rules.d/audit.rules"
  notify:
  - Restart auditd service
  when: ansible_distribution == 'Debian'

- name: Start auditd
  ansible.builtin.service:
    name: auditd
    state: started
    enabled: true
  when: ansible_distribution == 'Debian'

